basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /object:
    get:
      description: Get a value by key
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: Value
          schema:
            type: string
        "400":
          description: Missing Key
          schema:
            type: string
      summary: Get a value
swagger: "2.0"
