version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Изменяем внешний порт на 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

  api:
    build:
      context: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge